controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
contact_page:
    path: '/contact'
    controller: App\Controller\ProductsController::contact
    methods: ['GET']